import { StyleSheet } from "@react-pdf/renderer"

export const pdfColors = {
  text: "#0f172a",
  muted: "#64748b",
  border: "#e2e8f0",
  accent: "#7c3aed",
  accentSoft: "#f5f3ff",
  success: "#047857",
  danger: "#b91c1c",
  warning: "#b45309",
  tableHeaderBg: "#f8fafc",
  rowAlt: "#fafafa",
}

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 56,
    paddingHorizontal: 36,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: pdfColors.text,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  documentTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.text,
  },
  documentMeta: {
    fontSize: 9,
    color: pdfColors.muted,
    textAlign: "right",
  },
  headerDivider: {
    borderBottomWidth: 1,
    borderBottomColor: pdfColors.border,
    marginBottom: 16,
  },
  section: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.text,
    marginBottom: 6,
    paddingBottom: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: pdfColors.border,
  },
  athleteName: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
  },
  fieldGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  fieldBox: {
    width: "50%",
    paddingRight: 8,
    marginBottom: 4,
  },
  fieldLabel: {
    fontSize: 8,
    color: pdfColors.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 1,
  },
  fieldValue: {
    fontSize: 10,
    color: pdfColors.text,
  },
  table: {
    width: "100%",
    borderWidth: 0.5,
    borderColor: pdfColors.border,
    borderRadius: 2,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: pdfColors.tableHeaderBg,
    borderBottomWidth: 0.5,
    borderBottomColor: pdfColors.border,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.25,
    borderBottomColor: pdfColors.border,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  tableRowLast: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  tableRowTotal: {
    flexDirection: "row",
    backgroundColor: pdfColors.tableHeaderBg,
    borderTopWidth: 0.5,
    borderTopColor: pdfColors.border,
    paddingVertical: 5,
    paddingHorizontal: 4,
  },
  th: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.muted,
    textTransform: "uppercase",
  },
  td: {
    fontSize: 9,
    color: pdfColors.text,
  },
  tdMono: {
    fontSize: 9,
    fontFamily: "Courier",
    color: pdfColors.text,
  },
  tdMuted: {
    fontSize: 9,
    color: pdfColors.muted,
  },
  tdBold: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: pdfColors.text,
  },
  badge: {
    paddingVertical: 1,
    paddingHorizontal: 4,
    borderRadius: 2,
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    alignSelf: "flex-start",
  },
  badgeAccent: {
    backgroundColor: pdfColors.accentSoft,
    color: pdfColors.accent,
  },
  badgeSuccess: {
    backgroundColor: "#ecfdf5",
    color: pdfColors.success,
  },
  badgeWarning: {
    backgroundColor: "#fffbeb",
    color: pdfColors.warning,
  },
  badgeDanger: {
    backgroundColor: "#fef2f2",
    color: pdfColors.danger,
  },
  badgeMuted: {
    backgroundColor: "#f1f5f9",
    color: pdfColors.muted,
  },
  emptyState: {
    fontSize: 9,
    color: pdfColors.muted,
    fontStyle: "italic",
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderWidth: 0.5,
    borderColor: pdfColors.border,
    borderRadius: 2,
    borderStyle: "dashed",
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 36,
    right: 36,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: pdfColors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  footerLeft: {
    fontSize: 7,
    color: pdfColors.muted,
    maxWidth: "70%",
  },
  footerRight: {
    fontSize: 7,
    color: pdfColors.muted,
  },
})
